services:
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
    environment:
    - ACCEPT_FSL_EULA=1
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:1 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 226:* rmw
    - c 199:* rmw
    network_mode: host
    image: torizon/weston-vivante:3
  objectdetectiontorizon:
    privileged: true
    volumes:
    - /dev:/dev
    - /tmp:/tmp
    environment:
    - DISPLAY=:0
    depends_on:
    - weston
    image: lucasbernardestoradex/objectdetectiontorizon:cpu
version: "3.9"
