services:
  objectdetectiontorizon:
    depends_on:
    - weston
    environment:
    - DISPLAY=:0
    image: lucasbernardestoradex/objectdetectiontorizon:npu
    privileged: true
    volumes:
    - /dev:/dev
    - /tmp:/tmp
  weston:
    network_mode: host
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:1 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 226:* rmw
    - c 199:* rmw
    environment:
    - ACCEPT_FSL_EULA=1
    cap_add:
    - CAP_SYS_TTY_CONFIG
    image: torizon/weston-vivante:3
    volumes:
    - target: /tmp
      type: bind
      source: /tmp
    - target: /dev
      type: bind
      source: /dev
    - target: /run/udev
      type: bind
      source: /run/udev
version: "3.9"
