version: "3.9"
services:
  weston:
    image: torizon/weston-vivante:3
    # EULA required to run imx8 vivante graphic drivers
    # Pre-accept as we ask the user accept the EULA already.
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty1
      - 'c 4:1 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
      # ... for /dev/galcore device
      - 'c 199:* rmw'

  objectdetectiontorizon-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/videotfliteexample-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
    depends_on: 
      - weston
      
  objectdetectiontorizon:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/videotfliteexample:${TAG}
    environment:
      - DISPLAY=:0
    #devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
    #- "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true
    volumes:
     - /dev:/dev
     - /tmp:/tmp
    depends_on: 
      - weston
