services:
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    volumes:
    - source: /tmp
      type: bind
      target: /tmp
    - source: /dev
      type: bind
      target: /dev
    - source: /run/udev
      type: bind
      target: /run/udev
    image: torizon/weston-vivante:3
    network_mode: host
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:1 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 226:* rmw
    - c 199:* rmw
    environment:
    - ACCEPT_FSL_EULA=1
  objectdetectiontorizon:
    privileged: true
    volumes:
    - /dev:/dev
    - /tmp:/tmp
    image: lucasbernardestoradex/objectdetectiontorizon:arm64
    depends_on:
    - weston
    environment:
    - DISPLAY=:0
version: "3.9"
